### ISSUE TITLE
apache2 cookbook dependency is too old

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/passenger_apache2#53]
Current dependency is too restrictive: `depends 'apache2', '~> 1.0'`. It prevents anyone using this cookbook to have anything newer.

https://github.com/chef-cookbooks/passenger_apache2/blob/master/metadata.rb#L11

Chef Supermarket has 3.1.0 available: https://supermarket.chef.io/cookbooks/apache2.

This breaks our environment with berkshelf.

```
Generated at 2015-09-23 11:56:56 -0700
Net::HTTPServerException: 412 "Precondition Failed"
/opt/chef/embedded/lib/ruby/1.9.1/net/http.rb:2633:in `error!'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/http.rb:145:in `request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/http.rb:126:in `post'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/policy_builder/expand_node_object.rb:168:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/policy_builder/expand_node_object.rb:66:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:265:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:429:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application/client.rb:338:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application/client.rb:327:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application/client.rb:327:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in `<main>'
```

**Comment by irvingpop** [comment]
hey @haidangwa could you try this PR and tell us if it works in your environment?  https://github.com/chef-cookbooks/passenger_apache2/pull/45

**Comment by haidangwa** [comment]
@irvingpop Does seems to do the trick!

**Comment by tas50** [comment]
We're not depending on >= 2.0
